name: UpdateResolvers2022

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installing checkout
      uses: actions/checkout@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generating dns list
      run: |
        rm -f resolvers.txt
        wget https://public-dns.info/nameserver/us.txt -O /tmp/resolvers.txt
    
    - name: running dnsfaster
      uses: actions/setup-go@v3.3.1
      with:
          go-version: 1.19          
    - run: |     
        go install github.com/bp0lr/dnsfaster@latest
        dnsfaster --domain example.com --in /tmp/resolvers.txt --out "resolvers.txt" --tests 200 --workers 100 --filter-time 400 --filter-errors 20 --filter-rate 90 --save-dns
        
    - name: Commit resolvers.txt
      run: |
        pwd
        sudo git config --local user.email "action@github.com"
        sudo git config --local user.name "GitHub Action"
        sudo git add resolvers.txt
        sudo git commit -m "Update resolvers" -a
        sudo git push "https://bp0lr:${{ secrets.GITHUB_TOKEN }}@github.com/bp0lr/dmut-resolvers.git"
